Fix parsing of query with nested object
forcedotcom/sf-fx-runtime-java pull request #364
Opened 2022-12-16 20:47 UTC by colincasey

This modifies the parsing routine of data api queries to correctly parse result sets that include nested `Record` data.

Requires the following SDK change:
* https://github.com/forcedotcom/sf-fx-sdk-java/pull/106

[W-12157391](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00001FgZMwYAN/view)

2022-12-16 21:42 UTC, edmorley reviewed
Cancelling review since CI is failing

2023-01-10 10:39 UTC, Malax commented on sf-fx-runtime-java-sdk-impl-v1.1/src/test/java/com/salesforce/functions/jvm/runtime/sdk/DataApiImplTest.java
> +    assertThat(nestedRecord.getStringField("Name").get(), is("Guy Smiley"));
"Did somebody say air?"

2023-01-10 10:48 UTC, Malax commented
CI is failing due to sf-fx-sdk-java 1.1.1 not being released yet. After https://github.com/forcedotcom/sf-fx-sdk-java/pull/106 is merged an released, CI for this PR should start working again.

2023-01-10 10:52 UTC, edmorley commented
@Malax Is there a way the WIP over there can be tested here? It seems suboptimal to not be able to see passing CI before releasing things? Would merging that repository into this one (whilst still keeping the packages separate) help?

2023-01-10 12:48 UTC, Malax commented
@edmorley, moving the contents here is probably more complicated than installing the dependency "locally" in CI (`./mvnw install`). We could add this to the CI scripts for each unreleased version and the git ref that needs to be installed.

2023-01-10 13:00 UTC, Malax requested changes
Do we know if functions that depend on `sf-fx-sdk-java` in version `1.1.0` still work with the updated SDK 1.1 impl? If not, we probably need a separate SDK impl for `1.1.1`. On that note, I think the version mapping from SDK version to implementation JAR is missing for `1.1.1`. See `SalesforceFunctionsProjectFunctionsScanner`.

2023-01-10 15:33 UTC, colincasey commented on sf-fx-runtime-java-sdk-impl-v1.1/src/main/java/com/salesforce/functions/jvm/runtime/sdk/AbstractRecordAccessorImpl.java
> +  public Optional<Record> getRecordField(String name) {
naming does not have to be consistent with `getJsonFieldValue` which is **private**.  it has to be consistent with the **public SDK** methods from `RecordAccessor` such as:
* `getStringField`
* `getBinaryField`
* and so on...

hence, `getRecordField` 😄

2023-01-11 08:46 UTC, Malax commented on sf-fx-runtime-java-sdk-impl-v1.1/src/main/java/com/salesforce/functions/jvm/runtime/sdk/AbstractRecordAccessorImpl.java
> +  public Optional<Record> getRecordField(String name) {
That makes total sense, I didn't see that it's not another internal helper. Sorry for the noise! :)

2023-01-11 08:51 UTC, Malax requested changes
Implementation-weise this is good to go IMO. Do we want to add an integration test for a `1.1.1` SDK function as a smoke test? Seems valuable to me.

Next steps required before we can ship/approve this PR:
- Merge and release https://github.com/forcedotcom/sf-fx-sdk-java/pull/106
- Update `sf-fx-sdk-java`'s `1.1.1-SNAPSHOT` version to `1.1.1` in this PR
- Verify that CI passes

2023-01-19 14:59 UTC, Malax approved these changes

2023-01-19 15:26 UTC, merged